
            - name: Second
              completion_criteria:
                measure: "reward"
                thresholds: 2.0
                min_lesson_length: 100
                signal_smoothing: true
              value: 40.0

            - name: Fourth
              completion_criteria:
                measure: "reward"
                thresholds: 6.0
                min_lesson_length: 200
                signal_smoothing: true
              value: 10.0

            - name: Last
              value: 0.0
