#Tested with:
# python 3.8.5
# mlagents 8 (python)
# mlagents 1.4 (unity package)
# Unity 2020.1.10f
behaviors:
    AircraftLearner:
        trainer_type : ppo
        hyperparameters:
            batch_size: 2048
            beta: 1.0e-2
            buffer_size: 20480
            epsilon: 0.2
            lambd: 0.95
            learning_rate: 3.0e-4
            learning_rate_schedule: linear
            num_epoch: 3
        network_settings:
            hidden_units: 256
            memory_size: 256
            normalize: false
            num_layers: 2
            vis_encode_type: simple
        max_steps: 5.0e7
        time_horizon: 120
        summary_freq: 10000
        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.99
environment_parameters:
    checkpoint_radius:
        curriculum:
            - name: First
              completion_criteria:
                measure: reward
                behavior: AircraftLearner
                thresholds: 2.0
                min_lesson_length: 100
                signal_smoothing: true
              value: 50.0

            - name: Second
              completion_criteria:
                measure: reward
                behavior: AircraftLearner
                thresholds: 2.0
                min_lesson_length: 100
                signal_smoothing: true
              value: 30.0

            - name: Third
              completion_criteria:
                measure: reward
                behavior: AircraftLearner
                thresholds: 4.0
                min_lesson_length: 200
                signal_smoothing: true
              value: 20.0

            - name: Fourth
              completion_criteria:
                measure: reward
                behavior: AircraftLearner
                thresholds: 6.0
                min_lesson_length: 200
                signal_smoothing: true
              value: 10.0

            - name: Last
              value: 0.0

